
// HOME

export const HOME_SET_VIDEOS = "HOME_SET_VIDEOS";

export const HOME_SET_VIDEO = "HOME_SET_VIDEO";

export const HOME_SET_VIDEOS_STREAM_PREFERENCES = "HOME_SET_VIDEOS_STREAM_PREFERENCES";

export const HOME_ADD_VIDEO = "HOME_ADD_VIDEO";

export const HOME_DELETE_VIDEO = "HOME_DELETE_VIDEO";

// PLAYLISTS

export const PLAYLISTS_SET_PLAYLISTS = "PLAYLISTS_SET_PLAYLISTS";
export const PLAYLISTS_ADD_PLAYLIST = "PLAYLISTS_ADD_PLAYLIST";
export const PLAYLISTS_UPDATE_PLAYLIST = "PLAYLISTS_UPDATE_PLAYLIST";

// MY VIDEOS

export const MY_VIDEOS_SET_VIDEOS = "MY_VIDEOS_SET_VIDEOS";

// VIDEO

export const VIDEO_SET_VIDEO = "VIDEO_SET_VIDEO";
export const VIDEO_UNSET_VIDEO = "VIDEO_UNSET_VIDEO";

export const VIDEO_SET_CURRENT_BEST_STREAMING_LANGUAGE = "VIDEO_SET_CURRENT_BEST_STREAMING_LANGUAGE";
export const VIDEO_SET_CURRENT_BEST_STREAMING_QUALITY = "VIDEO_SET_CURRENT_BEST_STREAMING_QUALITY";

// GLOBAL

export const GLOBAL_DISPLAY_LOAD_MASK = "GLOBAL_DISPLAY_LOAD_MASK";
export const GLOBAL_DISMISS_LOAD_MASK = "GLOBAL_DISMISS_LOAD_MASK";

export const GLOBAL_DISPLAY_NOTIFICATION_SNACKBAR = "GLOBAL_DISPLAY_NOTIFICATION_SNACKBAR";
export const GLOBAL_DISMISS_NOTIFICATION_SNACKBAR = "GLOBAL_DISMISS_NOTIFICATION_SNACKBAR";

export const GLOBAL_DISPLAY_ALERT_DIALOG = "GLOBAL_DISPLAY_ALERT_DIALOG";
export const GLOBAL_DISMISS_ALERT_DIALOG = "GLOBAL_DISMISS_ALERT_DIALOG";

export const GLOBAL_DISPLAY_CONFIRM_DIALOG = "GLOBAL_DISPLAY_CONFIRM_DIALOG";
export const GLOBAL_DISMISS_CONFIRM_DIALOG = "GLOBAL_DISMISS_CONFIRM_DIALOG";

export const GLOBAL_DISPLAY_ADD_VIDEO_MODAL = "GLOBAL_DISPLAY_ADD_VIDEO_MODAL";
export const GLOBAL_DISMISS_ADD_VIDEO_MODAL = "GLOBAL_DISMISS_ADD_VIDEO_MODAL";

export const GLOBAL_DISPLAY_CREATE_PLAYLIST_MODAL = "GLOBAL_DISPLAY_CREATE_PLAYLIST_MODAL";
export const GLOBAL_DISMISS_CREATE_PLAYLIST_MODAL = "GLOBAL_DISMISS_CREATE_PLAYLIST_MODAL";

export const GLOBAL_ADD_VIDEO_MODAL_SET_VIDEO_TITLE = "GLOBAL_ADD_VIDEO_MODAL_SET_VIDEO_TITLE";
export const GLOBAL_ADD_VIDEO_MODAL_SET_SUGGESTIONS = "GLOBAL_ADD_VIDEO_MODAL_SET_SUGGESTIONS";
export const GLOBAL_ADD_VIDEO_MODAL_SET_SUGGESTIONS_POSSIBLE = "GLOBAL_ADD_VIDEO_MODAL_SET_SUGGESTIONS_POSSIBLE";
export const GLOBAL_ADD_VIDEO_MODAL_SET_CURRENT_VIDEO = "GLOBAL_ADD_VIDEO_MODAL_SET_CURRENT_VIDEO";
export const GLOBAL_ADD_VIDEO_MODAL_SET_VIDEO_URL = "GLOBAL_ADD_VIDEO_MODAL_SET_VIDEO_URL";

export const GLOBAL_AUTH_SUCCESS = "GLOBAL_AUTH_SUCCESS";
export const GLOBAL_AUTH_FAILURE = "GLOBAL_AUTH_FAILURE";

export const GLOBAL_SETTINGS_SET_LANGUAGE = "GLOBAL_SETTINGS_SET_LANGUAGE";
export const GLOBAL_SETTINGS_SET_USERNAME = "GLOBAL_SETTINGS_SET_USERNAME";
export const GLOBAL_SETTINGS_SET_EMAIL = "GLOBAL_SETTINGS_SET_EMAIL";

export const GLOBAL_SETTINGS_SET_DARK_MODE = "GLOBAL_SETTINGS_SET_DARK_MODE";
export const GLOBAL_SETTINGS_SET_PREFERRED_STREAM_LANGUAGE = "GLOBAL_SETTINGS_SET_PREFERRED_STREAM_LANGUAGE";
export const GLOBAL_SETTINGS_SET_PREFERRED_STREAM_QUALITY = "GLOBAL_SETTINGS_SET_PREFERRED_STREAM_QUALITY";
export const GLOBAL_SETTINGS_SET_PRINCIPAL_COLOR = "GLOBAL_SETTINGS_SET_PRINCIPAL_COLOR";
export const GLOBAL_SETTINGS_SET_SECONDARY_COLOR = "GLOBAL_SETTINGS_SET_SECONDARY_COLOR";

export const GLOBAL_RESET_SETTINGS_CHANGES = "GLOBAL_RESET_SETTINGS_CHANGES";
export const GLOBAL_APPLY_SETTINGS_CHANGES = "GLOBAL_APPLY_SETTINGS_CHANGES";

export const GLOBAL_SET_NAVIGATION = "GLOBAL_SET_NAVIGATION";
export const GLOBAL_SET_MOBILE_DRAWER_IS_OPEN = "GLOBAL_SET_MOBILE_DRAWER_IS_OPEN";

export const GLOBAL_PLAYLISTS_IS_LOAD = "GLOBAL_PLAYLISTS_IS_LOAD";
export const GLOBAL_HOME_IS_LOAD = "GLOBAL_HOME_IS_LOAD";
export const GLOBAL_MY_VIDEOS_IS_LOAD = "GLOBAL_MY_VIDEOS_IS_LOAD";

export const GLOBAL_RESET = "GLOBAL_RESET";