version: '3.1'

services:
  app:
    build: .
    command: npm run build
    environment:
      NODE_ENV: development
      PORT: 3001
    ports:
      - '3001:3001'
    volumes:
      - .:/home/app/appDir
      - /home/app/appDir/node_modules
